In [1]:
import numpy as np

In [4]:
arr1=np.random.randint(1,10,(3,4))
arr2=np.random.randint(1,10,(3,4))

In [5]:
arr1

array([[2, 3, 3, 7],
       [7, 7, 8, 8],
       [1, 2, 9, 5]])

In [6]:
arr2

array([[8, 4, 1, 1],
       [3, 4, 9, 9],
       [5, 6, 9, 1]])

In [7]:
arr1+arr2

array([[10,  7,  4,  8],
       [10, 11, 17, 17],
       [ 6,  8, 18,  6]])

In [8]:
arr1-arr2

array([[-6, -1,  2,  6],
       [ 4,  3, -1, -1],
       [-4, -4,  0,  4]])

In [9]:
arr1>arr2

array([[False, False,  True,  True],
       [ True,  True, False, False],
       [False, False, False,  True]])

In [10]:
~arr1

array([[ -3,  -4,  -4,  -8],
       [ -8,  -8,  -9,  -9],
       [ -2,  -3, -10,  -6]])

In [13]:
arr1//arr2

array([[0, 0, 3, 7],
       [2, 1, 0, 0],
       [0, 0, 1, 5]])

In [14]:
arr1**arr2

array([[      256,        81,         3,         7],
       [      343,      2401, 134217728, 134217728],
       [        1,        64, 387420489,         5]])

In [15]:
## numpy string functions 

In [17]:
arr=np.array(['pw','skills'])
arr

array(['pw', 'skills'], dtype='<U6')

In [19]:
arr1=np.char.upper(arr)
arr1

array(['PW', 'SKILLS'], dtype='<U6')

In [21]:
id(arr)==id(arr1)

False

In [22]:
np.char.capitalize(arr)

array(['Pw', 'Skills'], dtype='<U6')

In [24]:
np.char.count(arr,'s')

array([0, 2])

In [26]:
np.char.capitalize(arr)

array(['Pw', 'Skills'], dtype='<U6')

In [27]:
np.char.title(arr)

array(['Pw', 'Skills'], dtype='<U6')

In [30]:
arr1=np.random.randint(1,10,(3,4))
arr1

array([[6, 4, 2, 9],
       [7, 6, 3, 4],
       [2, 4, 1, 4]])

In [31]:
arr2=np.random.randint(1,10,(3,4))
arr2

array([[4, 3, 6, 1],
       [9, 8, 2, 7],
       [6, 2, 3, 4]])

In [33]:
np.sin(arr1)

array([[-0.2794155 , -0.7568025 ,  0.90929743,  0.41211849],
       [ 0.6569866 , -0.2794155 ,  0.14112001, -0.7568025 ],
       [ 0.90929743, -0.7568025 ,  0.84147098, -0.7568025 ]])

In [34]:
np.var(arr1)

4.888888888888889

In [36]:
np.std(arr1)

2.211083193570267

In [37]:
np.std(arr2)

2.465033242958173

In [39]:
np.sum((arr1,arr2))

107

In [42]:
np.subtract(arr1,arr2)

array([[ 2,  1, -4,  8],
       [-2, -2,  1, -3],
       [-4,  2, -2,  0]])

In [43]:
np.add(arr1,arr2)

array([[10,  7,  8, 10],
       [16, 14,  5, 11],
       [ 8,  6,  4,  8]])

In [44]:
np.mod(arr1,arr2)

array([[2, 1, 2, 0],
       [7, 6, 1, 4],
       [2, 0, 1, 0]])

In [47]:
np.sqrt(arr1)

array([[2.44948974, 2.        , 1.41421356, 3.        ],
       [2.64575131, 2.44948974, 1.73205081, 2.        ],
       [1.41421356, 2.        , 1.        , 2.        ]])

In [49]:
## sorting and searching 
arr1

array([[6, 4, 2, 9],
       [7, 6, 3, 4],
       [2, 4, 1, 4]])

In [50]:
np.sort(arr1)

array([[2, 4, 6, 9],
       [3, 4, 6, 7],
       [1, 2, 4, 4]])

In [55]:
arr3=np.array([2,4,6,8,9])


In [56]:
np.searchsorted(arr3,5)

2

In [60]:
arr4=np.array([[1,2],[3,4,],[5,8]])
arr4

array([[1, 2],
       [3, 4],
       [5, 8]])

In [65]:
np.extract(arr4>4,arr4)

array([5, 8])

In [66]:
arr1

array([[6, 4, 2, 9],
       [7, 6, 3, 4],
       [2, 4, 1, 4]])

In [70]:
np.bytes_(arr1)

b'\x06\x00\x00\x00\x04\x00\x00\x00\x02\x00\x00\x00\t\x00\x00\x00\x07\x00\x00\x00\x06\x00\x00\x00\x03\x00\x00\x00\x04\x00\x00\x00\x02\x00\x00\x00\x04\x00\x00\x00\x01\x00\x00\x00\x04'

## matrix computations in numpy

In [72]:
import numpy.matlib as nm

In [73]:
   nm.zeros(2)

matrix([[0., 0.]])

In [74]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

### numpy linear algebra 

In [75]:
ar1=np.random.randint(1,10,(3,4))
ar1

array([[2, 3, 6, 8],
       [1, 2, 4, 9],
       [6, 4, 1, 3]])

In [76]:
ar2=np.random.randint(1,10,(3,4))
ar2

array([[8, 5, 7, 1],
       [8, 5, 8, 2],
       [6, 5, 8, 7]])

In [77]:
ar1*ar2

array([[16, 15, 42,  8],
       [ 8, 10, 32, 18],
       [36, 20,  8, 21]])

In [78]:
ar1@ar2

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 4)

In [80]:
ar11=np.array([[1,2],[4,5]])
ar12=np.array([[1,3],[8,8]])


In [81]:
ar11

array([[1, 2],
       [4, 5]])

In [82]:
ar12

array([[1, 2],
       [4, 5]])

In [83]:
ar11 @ar12

array([[ 9, 12],
       [24, 33]])

In [84]:
a=np.array([[7,5,-3],[2,-5,2],[5,3,-7]])
a

array([[ 7,  5, -3],
       [ 2, -5,  2],
       [ 5,  3, -7]])

In [85]:
b=np.array([16,-8,0])
b

array([16, -8,  0])

In [86]:
np.linalg.solve(a,b)

array([1.11304348, 2.85217391, 2.0173913 ])

In [87]:
a=np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [88]:
np.linalg.det(a)

-2.0000000000000004

In [90]:
np.linalg.inv(a)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])