In [1]:
import numpy as np

In [3]:
np.version

<module 'numpy.version' from 'F:\\Anaconda3\\lib\\site-packages\\numpy\\version.py'>

In [4]:
l=[1,2,3,'F']
l

[1, 2, 3, 'F']

In [5]:
np.array(l)

array(['1', '2', '3', 'F'], dtype='<U11')

In [6]:
l1=[1,2,3,4]


In [7]:
np.array(l1)

array([1, 2, 3, 4])

In [8]:
np.matrix([1,2,3,4])

matrix([[1, 2, 3, 4]])

In [9]:
np.matrix([[[1,2],[5,6],[7,8]]])

ValueError: matrix must be 2-dimensional

In [10]:
np.array([[[1,2],[4,5],[6,7]]])

array([[[1, 2],
        [4, 5],
        [6, 7]]])

In [11]:
#more way to convert list into array 
np.asarray([1,2,3,4])


array([1, 2, 3, 4])

In [13]:
np.asanyarray([1,2,3,4])

array([1, 2, 3, 4])

In [14]:
np.asanyarray([[1,2,3],[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
## matrix is the subclass of an array 
## now when to use array and when to use matrix ?


In [16]:
np.matrix([[1,2,3,4]])

matrix([[1, 2, 3, 4]])

In [17]:
np.asanyarray(np.matrix([[1,2,3,4]]))

matrix([[1, 2, 3, 4]])

In [19]:
np.array(np.matrix([[1,2,3,4]]))

array([[1, 2, 3, 4]])

In [22]:
t=([1,2,3],[5,6,7])

In [23]:
np.array(t)

array([[1, 2, 3],
       [5, 6, 7]])

In [24]:
a=5
np.array(5)

array(5)

In [25]:
## deep copy and shallow copy 

In [27]:
l=[1,2,3,4,5]
arr=np.array(l)
arr

array([1, 2, 3, 4, 5])

In [29]:
arr[0]=23

In [30]:
arr

array([23,  2,  3,  4,  5])

In [31]:
arr

array([23,  2,  3,  4,  5])

In [36]:
l1=np.array([1,4,2,5])
arr1=np.array(l1)
arr1

array([1, 4, 2, 5])

In [37]:
ar=arr1
ar

array([1, 4, 2, 5])

In [38]:
arr1[0]=78
arr1

array([78,  4,  2,  5])

In [39]:
ar

array([78,  4,  2,  5])

In [40]:
l=[[1,3],[4,5]]
arr1=np.array(l)
arr1

array([[1, 3],
       [4, 5]])

In [41]:
arr12=arr1
arr12

array([[1, 3],
       [4, 5]])

In [43]:
arr1[0][0]=4567
arr1

array([[4567,    3],
       [   4,    5]])

In [44]:
arr12

array([[4567,    3],
       [   4,    5]])

In [46]:
arr13=arr1.copy()
arr13

array([[4567,    3],
       [   4,    5]])

In [47]:
arr1[0][1]=6789
arr1

array([[4567, 6789],
       [   4,    5]])

In [48]:
arr13

array([[4567,    3],
       [   4,    5]])

In [49]:
## multiple ways to generate teh array 

In [61]:
a1=np.fromfunction(lambda i,j:i==j,shape=(3,3))
a1

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [62]:
list([i for i in range(5)])

[0, 1, 2, 3, 4]

In [65]:
var=((i*i for i in range(5)))

In [67]:
np.fromiter(var,float)

array([ 0.,  1.,  4.,  9., 16.])

In [76]:
np.fromstring('suhani,45,67',sep=',')

C:\Users\Vaishnavi\AppData\Local\Temp\ipykernel_2220\1121570043.py:1: DeprecationWarning: string or file could not be read to its end due to unmatched data; this will raise a ValueError in the future.
  np.fromstring('suhani,45,67',sep=',')


array([], dtype=float64)

In [77]:
arr.shape

(5,)

In [78]:
arr1.dtype

dtype('int32')

In [79]:
l=[1,2,3,'vaish']
arr=np.array(l)
arr.dtype

dtype('<U11')

In [80]:
l=[1,2,3]
arr=np.array(l)
arr.dtype

dtype('int32')

In [81]:
list(range(1.0,2.10))

TypeError: 'float' object cannot be interpreted as an integer

In [83]:
np.arange(0.1,10.2)

array([ 0.1,  1.1,  2.1,  3.1,  4.1,  5.1,  6.1,  7.1,  8.1,  9.1, 10.1])

In [85]:
np.arange(1.0,2.0)

array([1.])

In [87]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [92]:
np.logspace(1,3,base=2)

array([2.        , 2.05739147, 2.11642982, 2.17716233, 2.2396376 ,
       2.30390564, 2.37001791, 2.43802731, 2.50798829, 2.57995685,
       2.65399061, 2.73014882, 2.80849244, 2.88908419, 2.97198858,
       3.05727197, 3.14500263, 3.23525079, 3.32808868, 3.42359063,
       3.52183307, 3.62289466, 3.72685628, 3.83380115, 3.94381489,
       4.05698555, 4.17340372, 4.2931626 , 4.41635805, 4.54308869,
       4.67345595, 4.8075642 , 4.94552078, 5.08743612, 5.23342383,
       5.38360077, 5.53808714, 5.69700662, 5.8604864 , 6.02865736,
       6.2016541 , 6.37961511, 6.56268285, 6.75100385, 6.94472885,
       7.14401294, 7.34901563, 7.55990103, 7.77683793, 8.        ])

In [93]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [100]:
a=np.zeros((3,2,2))
a

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [103]:
a.size

12

In [110]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])