In [1]:
import numpy as np

In [7]:
np.empty((3,3))

array([[0.000e+000, 0.000e+000, 0.000e+000],
       [0.000e+000, 0.000e+000, 7.727e-321],
       [0.000e+000, 0.000e+000, 0.000e+000]])

In [9]:
ar=np.ones((2,2))
ar

array([[1., 1.],
       [1., 1.]])

In [10]:
np.add(ar,3)

array([[4., 4.],
       [4., 4.]])

In [17]:
import pandas as pd
arr1=np.ones((4,4))
arr1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [18]:
pd.DataFrame(arr1)

0    1    2    3
0  1.0  1.0  1.0  1.0
1  1.0  1.0  1.0  1.0
2  1.0  1.0  1.0  1.0
3  1.0  1.0  1.0  1.0

In [20]:
np.eye(3,dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [35]:
import random 
random.choice((4,5,2,1,3))

4

In [40]:
random.choice("vaishnav")

'v'

In [42]:
random.randrange(1,10)

5

In [47]:
random.randint(1,10)

6

In [49]:
np.random.randint(1,10,10)

array([7, 3, 8, 9, 5, 6, 1, 4, 6, 3])

In [56]:
arr=np.random.randint((4,3),size=(3,4))

ValueError: shape mismatch: objects cannot be broadcast to a single shape.  Mismatch is between arg 1 with shape (2,) and arg 2 with shape (3, 4).

In [55]:
arr

array([2, 1])

In [57]:
arr1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [59]:
np.random.randint((3,4),)

array([0, 0, 4])

In [60]:
arr1.reshape(8,2)

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [66]:
arr1.reshape(2,-1)

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [68]:
arr1.reshape(-1,2)

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [72]:
arr1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [77]:
arr1.reshape(8,2).base

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [89]:
arr1.reshape(1,2,2,4)

array([[[[1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.]]]])

In [91]:
l1=[1,2,3,4]
arr=np.array(l1)
arr

array([1, 2, 3, 4])

In [92]:
arr.ndim

1

In [94]:
arr2=np.array([[2,3],[3,4]])
arr2

array([[2, 3],
       [3, 4]])

In [95]:
arr2.ndim

2

In [98]:
arr2=np.zeros((3,4))
arr2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [99]:
arr2.ndim

2

In [100]:
arr3=np.zeros((1,3,4))
arr3

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])